name: Scan and build new version tags
on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"
jobs:
  scanAndBuild:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: auth
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: buildNewTags
      run: |
        skip_tags="v.1.3.0-rc2 v.1.3.1-pre v1.5.1-rc1 v1.5.2-rc1 v1.5.2-rc2 v1.5.3-rc1 v1.5.4-rc1 v1.6.0-rc1 v2.0.0-alpha v2.0.1-alpha"
        token=$(curl -su ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} https://ghcr.io/token\?scope\="repository:${{ github.repository }}:pull" | jq -r .token)
        docker_tags=$(curl -sH "Authorization: Bearer $token" https://ghcr.io/v2/${{ github.repository }}/tags/list | jq -r 'try(.tags[])')
        binary_tags=$(git ls-remote --tags https://github.com/BitcannaGlobal/bcna | awk '{print $2}' | cut -d/ -f3 | tr '\n' ' ')
        new_tags=($(echo $skip_tags $skip_tags $docker_tags $docker_tags $binary_tags | tr ' ' '\n' | sort | uniq -u))
        echo ${new_tags[@]}
        for tag in ${new_tags[@]}
        do
          docker build --no-cache --build-arg tag_version=$tag -t ghcr.io/${{ github.repository }}:$tag .
          docker push ghcr.io/${{ github.repository }}:$tag
        done
      shell: bash